name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@v1
        with:
          persist-credentials: true

      - name: Update sponsors
        run: pnpm exec sponsorkit --dir .
        env:
          SPONSORKIT_GITHUB_LOGIN: sxzz
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: update sponsors.svg [ci skip]'
          add: 'sponsors.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge Cache
        run: node purge-cache.ts
